### PR TITLE
feature: update german localization

### LINKED ISSUE #233: IMPROVE - German Localization
## Localizations: update German translation
The German translation is outdated and needs some work.

## Describe alternatives you've considered
n/a

### PR DESCRIPTION
**Pull request by appfrosch**
# What it Does
* Closes #233
* Updates the German localization

### CODE REVIEW

**Review by mikaelacaron — CHANGES_REQUESTED** [review]
Thanks for the update! Can you resolve the merge conflicts please?

**Comment by appfrosch** [comment]
I had some trouble with this one, but that should be fixed now 😅

**Review by mikaelacaron — CHANGES_REQUESTED** [review]
Please update this branch with `dev` and resolve merge conflicts. I wouldn't expect this many changes given German is 86% translated on `dev`


After you're done, click the re-review button.

**Comment by appfrosch** [comment]
Hmmm-it seems as though I did quite a mess here...

I will discard this PR and start over again.

**Pull request closed without merging**
