### PR TITLE
Update Contributor Tests.swift

### PR DESCRIPTION
**Pull request by ooye-sanket**
# What it Does

Adds a new test case testNewFeature to the ContributorTests suite.
Tests encoding and decoding of a Contributor object with custom data.
This change enhances testing by covering object encoding and decoding.

# How I Tested

Added a new test case testNewFeature.
Prepared custom test data for a Contributor object.
Encoded and decoded the object.
Checked if the decoded object is equal to the original.

# Notes
This change improves the test suite's coverage by including an additional test case for encoding and decoding a Contributor object with customized data.

# Screenshot
This note makes it clear that the absence of visual documentation is due to technical constraints and directs readers to review the code directly for the changes.

### CODE REVIEW

**Comment by mikaelacaron** [comment]
@sanketkalekar Is this connected to any issue?

**Comment by ooye-sanket** [comment]
NO, but added new feature to it

**Comment by mikaelacaron** [comment]
Next time please make an issue to describe what you want to work on, before just opening a PR, thank you!

**Comment by ooye-sanket** [comment]
It will be merged or not?!

**Comment by mikaelacaron** [comment]
> It will be merged or not?!

I'm not sure yet, I haven't reviewed it. I will look at it when I can

**Review by mikaelacaron — COMMENTED** [review]
I am going to close this PR, you haven't tested something new that isn't already there.

`testContributorDecoding` and `testContributorEncoding` are already testing these concepts.

**Pull request closed without merging**
