### PR TITLE
IMPROVE - Error Handling Adding a Maintenance Event #9

### PR DESCRIPTION
**Pull request by narendrajagne**
gray out the "Add" button, until the user has filled in the title

### CODE REVIEW

**Comment by narendrajagne** [comment]
gray out the "Add" button, until the user has filled in the title

**Review by mikaelacaron — APPROVED** [review]
Nice and simple! My preference is for modifiers to be on a new line, btw as a note for the future

@narendrajagne  Next time please fill out the PR template properly and not delete everything that's in it, even for a simple PR

**Comment by narendrajagne** [comment]
Hii, Where will put #Hacktoberfest-accepted tag ?

**Comment by mikaelacaron** [comment]
@narendrajagne it's not needed because it was merged

**Pull request merged**
