### PR TITLE
Setup Instructions for Firebase local emulator 

### PR DESCRIPTION
**Pull request by nnethaji**
# What it Does
* Closes issue #14 
- Added instructions on Firebase local emulator setup
- Added link to simpler and easier to follow style guide for Swift
- Updated README.md and CONTRIBUTING.md

### CODE REVIEW

**Comment by mikaelacaron** [comment]
@nnethaji Do you want this to be counted for Hacktoberfest? If so, I don't think if you open the PR early (before October 1st) that it will count

**Comment by mikaelacaron** [comment]
@nnethaji can you please let me know in the next 12 hours your status on this? Otherwise I'll be closing this PR and assigning someone else to #14 to allow someone else to work on this issue

**Comment by nnethaji** [comment]
​Hello there,
​Sorry, was busy. I do not want this to count for the Hacktober fest. Thank you!
On Oct 3 2023, at 4:58 AM, Mikaela Caron ***@***.***> wrote:
[External Email]

@nnethaji<https://github.com/nnethaji> can you please let me know in the next 12 hours your status on this? Otherwise I'll be closing this PR and assigning someone else to #14<https://github.com/mikaelacaron/Basic-Car-Maintenance/issues/14> to allow someone else to work on this issue

**Comment by mikaelacaron** [comment]
@nnethaji Thank you for letting me know!

**Comment by mikaelacaron** [comment]
@nnethaji Do you have time to upgrade your PR, to actually use the emulator in the project in place of Firebase, when developing locally? If not, I'll close this PR and someone else can work on this issue

**Comment by nnethaji** [comment]
You can close the PR. Thanks
​
On Oct 4 2023, at 12:54 AM, Mikaela Caron ***@***.***> wrote:
[External Email]

@nnethaji<https://github.com/nnethaji> Do you have time to upgrade your PR, to actually use the emulator in the project in place of Firebase, when developing locally? If not, I'll close this PR and someone else can work on this issue

**Pull request closed without merging**
