### PR TITLE
Brazilian Portuguese localization added

### PR DESCRIPTION
**Pull request by horacio3m**
# What it Does
* Adds Brazilian Portuguese language localization

# How I Tested
* Set system language to Portuguese and start app

# Notes
* I fixed the issue on readme.md 

# Screenshot
Captura de Tela 2023-10-24 às 22 49 45

### CODE REVIEW

**Comment by horacio3m** [comment]
I closed the previous pull request and open this one fixing all issues and merge conflicts.

**Review by mikaelacaron — COMMENTED** [review]
I haven't looked at this in-depth, but do you know why some of the Russian translations are being overwritten? and the Ukrainian ones too??
Typically it would add `pt-BR` and then the translation to each key?

**Comment by horacio3m** [comment]
@mikaelacaron Looking more closely at the commit I made, it seems that when I create a new language, it is overwriting the last one, which is Russian
Captura de Tela 2023-10-25 às 20 09 33
Captura de Tela 2023-10-25 às 20 09 42

**Comment by mikaelacaron** [comment]
hmmmm that's weird.... it definitely shouldn't overwrite anything, and it's weird that it would suddenly happen (cause it hasn't happened with the other languages)

can you try again, (on a new branch from `dev`), and only do a few words at a time, and commit often, which should prevent a giant overwrite at once

**Comment by mikaelacaron** [comment]
The commits doesn't really matter, because I squash them all anyways when I merge PRs

**Comment by horacio3m** [comment]
> hmmmm that's weird.... it definitely shouldn't overwrite anything, and it's weird that it would suddenly happen (cause it hasn't happened with the other languages)
> 
> can you try again, (on a new branch from `dev`), and only do a few words at a time, and commit often, which should prevent a giant overwrite at once

Im opening a new branch to test this issue.

**Comment by mikaelacaron** [comment]
@horaciomota Be sure you branch _from_ `dev`!

**Comment by horacio3m** [comment]
I'm investigating the issue, but I'm really not understanding it. Even when I just create the language (without adding any words), it overwrites a lot of things. I'm looking for a solution for this

Captura de Tela 2023-10-25 às 21 23 22

**Comment by horacio3m** [comment]
y theory: I believe that when you specifically create the Portuguese (Brazil or Portugal) language within the Basic-Car-Maintenance.xcodeproj/project.pbxproj, it is added to the list of languages as 'pt-br' with quotes (" "), and no other language is added with quotes.
I tested by adding the Danish language, and no files were rewritten as expected. I believe it's a specific issue with the Portuguese language. I'm still trying to resolve the problem.
I cloused this merge for now. I really trying to solve this conflict
Captura de Tela 2023-10-25 às 22 06 23

**Comment by mikaelacaron** [comment]
> I'm investigating the issue, but I'm really not understanding it. Even when I just create the language (without adding any words), it overwrites a lot of things. I'm looking for a solution for this
> 
> Captura de Tela 2023-10-25 às 21 23 22

This image specifically isn't overwriting anything, it's indenting lines 73 and 74, and adding a new line pt-BR on 577


> I believe that when you specifically create the Portuguese (Brazil or Portugal) language within the Basic-Car-Maintenance.xcodeproj/project.pbxproj, it is added to the list of languages as 'pt-br' with quotes (" "), and no other language is added with quotes.

This seems like it happens for any language that uses a hyphen, and yours just seems like the first one that has that.

**Comment by mikaelacaron** [comment]
@horaciomota Go ahead and open the PR! I know what's happening. So the localizations are in alphabetical order, and `pt-BR` comes before `uk` (Ukrainian) and `ru`  (Russian)

So your translation is "replacing that line" but what's really happening is that it's adding your translations and shifting others down, so that's why it looks like that

**Pull request closed without merging**
