### PR TITLE
CI script to run unit tests

### PR DESCRIPTION
**Pull request by am2089**
# What it Does
CI script to run unit test
* Closes #issue 53
* Triggers CI script to run unit test manually

# How I Tested
Can't be tested until accepted by @mikaelacaron

### CODE REVIEW

**Comment by mikaelacaron** [comment]
Does this replace #95 ? if so close that PR, and be sure to update the description and title properly for this PR @am2089

**Comment by am2089** [comment]
Ohh no it’s for #53 since it wouldn’t build the CI for the unit test.Sent from my iPhoneOn Oct 8, 2023, at 3:19 PM, Mikaela Caron ***@***.***> wrote:﻿
Does this replace #95 ? if so close that PR, and be sure to update the description and title properly for this PR @am2089

**Comment by mikaelacaron** [comment]
@am2089 I'm referencing another PR, because you created two now, does this replace your first PR?

**Comment by am2089** [comment]
Yes this replaces the first oneSent from my iPhoneOn Oct 8, 2023, at 3:42 PM, Mikaela Caron ***@***.***> wrote:﻿
@am2089 I'm referencing another PR, because you created two now, does this replace your first PR?

**Comment by mikaelacaron** [comment]
@am2089 it looks like this still isn't running, has it worked on your fork repo?

Also I think considering it hasn't worked, we could instead look at using fastlane for this, you're welcome to try to tackle this, issue #54 is working on something similar. If you're not familiar or don't want to work on this issue, no worries, go to the issue and un-assign yourself

**Pull request closed without merging**
