### PR TITLE
feat: Add Onboarding View (only UI)

### PR DESCRIPTION
**Pull request by maartinj**
# What it Does
* Related to https://github.com/mikaelacaron/Basic-Car-Maintenance/issues/40
* When app will be launch for the first time, will be presented 2 onboarding screens
* 1st screen present the highlighted features of the app
* 2nd screen allows to add basic data about first car
* This pull request contains only UI (logic to remember app state whether User launched app for the first time or launched already, is commented. No more different logic is not included)
* 1st and 3rd bullet point description had to be shortened due to SwiftLint policy

# How I Tested
* Run the application in Preview
* Run the application in Simulator (with temporary logic turned on to show whether WelcomeScreen is loading when app is launched for the first time)
* Check whether view components are shown correctly based on the design created in Figma

# Notes
* May need further updates to include logic when app is launched for the first time and to remember to not load onboarding screens when app is launched again

# Screenshots

# Screencast
Works only with temporary logic turned on (video only shows how Onboarding screens looks in simulator)

https://github.com/mikaelacaron/Basic-Car-Maintenance/assets/53284922/f3f32ac7-10ca-493f-a851-57430313739f

### CODE REVIEW

**Comment by mikaelacaron** [comment]
Thanks for the PR! I see this! I haven't had time yet to review it @maartinj

**Review by mikaelacaron — APPROVED** [review]
Finally getting around to finishing up this app! Thanks so much for contributing and your patience!!

tiny note on your PR, I changed the name of the views to `WelcomeView` and `WelcomeViewAddVehicle`, rather than `WelcomeScreen` and `WelcomeScreenDetails` and when making the `pointView` the `title` and `subTitle` should be a `LocalizedStringKey`, which makes the strings get added to the `Localizable.xcstrings` file better. and I noticed there were several strings missing from that file, which makes me think you made the SwiftUI view, but then forgot to build the project

But again thank you for contributing and thanks for waiting so long for me to get to this!

**Comment by maartinj** [comment]
@mikaelacaron Sure, you welcome 😊 Happy to help with other tasks 👍

**Comment by mikaelacaron** [comment]
Thank you! I can message you here or DM me, I have very specific issues I want to do to wrap everything up and get it shipped this month

**Pull request merged**
