### PR TITLE
Set DocC naming to `BasicCarMaintenance`

### LINKED ISSUE #198: DocC Naming
Does anyone know, why the DocC documentation shows as underscores for the name`Basic_Car_Maintenance`?

Is it possible to change it to `Basic-Car-Maintenance` or just `BasicCarMaintenance`?

Would the script `build-docc.sh` need to be updated if this can be changed?

Screenshot 2023-10-21 at 1 41 34 AM

### PR DESCRIPTION
**Pull request by hanhqvu**
# What it Does
* Closes #198
* This PR will set the DocC generated title with CamelCase, `BasicCarMaintenance`

# How I Tested
* Ran DocC build command in local environment

# Notes
* N/A

# Screenshot
image

### CODE REVIEW

**Comment by mikaelacaron** [comment]
@hanhqvu can you screenshot where this setting is in Xcode? because I can't tell from only the `pbxproj` file

**Comment by hanhqvu** [comment]
@mikaelacaron The settings is under `Build Settings` for the main app target, it is easier to search with the keyword `product module name`

image

**Review by mikaelacaron — APPROVED** [review]
I love that this was quick fix! I'm actually going to mark this as `hacktoberfest-accepted` and make this as a change to one of the `xcconfig` files later after Hacktoberfest. I'll leave it for now

**Comment by mikaelacaron** [comment]
Going to close this, because I'm going to update this value probably from an xcconfig file, also I think it affects the `build-docc.sh` file that's used for deploying to the web with GitHub Actions

Thanks so much for working on this last year! (haha I'm finally getting around to wrapping everything up to deploy before Hacktoberfest this year)

**Pull request closed without merging**
