### PR TITLE
Change the NavigationTitle of the EditEventDetailView

### LINKED ISSUE #136: Change the NavigationTitle of the `EditEventDetailView`
## Describe the feature you want to improve
* The `EditEventDetailView` says `Add Maintenance` as the title but instead it should say `Update Maintenance` because we aren't adding something new, but updating values

## Describe alternatives you've considered
* N/A

## Screenshot

https://github.com/mikaelacaron/Basic-Car-Maintenance/assets/22946902/6f34035c-5b84-45a4-8aa5-8aaee8acc2a2

### PR DESCRIPTION
**Pull request by shanan-P**

### CODE REVIEW

**Comment by mikaelacaron** [comment]
@pipliya Please update your PR properly following the PR template as it was written, don't erase everything. And you did not comment on this issue saying you would like to work on it, as it states to do in the [README](https://github.com/mikaelacaron/Basic-Car-Maintenance#readme). If you do this again, you will not be allowed to work on this project. Thank you.

Also are you new to iOS development? This issue is labeled `first-timers-only` and is only for beginners

**Comment by shanan-P** [comment]
Thank you for your clarification. Yes, I am first timer in swift but cannot test it at this moment. Please let me update this PR accordingly and close it. This project looks good, will definitely work on this project in future!

**Comment by mikaelacaron** [comment]
Do not open a PR unless you can test it, and please read through the instructions in the [README](https://github.com/mikaelacaron/Basic-Car-Maintenance#readme). If you still want to work on that issue, comment on it in the Issues, to let others know someone is working on that issue

**Comment by mikaelacaron** [comment]
@pipliya I am assigning someone else this issue, because they commented on it, as you are supposed to. I'll be creating new issues as the month goes on for Hacktoberfest, and you're welcome to find a new issue to work on

**Comment by shanan-P** [comment]
Yeah Sure. Thanks!

**Pull request closed without merging**
